language: ruby
rvm:
  - 1.9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec serve 2>/dev/null &
  - sleep 2

script: phantomjs ./test/run-qunit.js "http://localhost:4000/test/tes.html"